---
title: "Untitled"
output: pdf_document
date: "2023-07-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source("/home/carson/Desktop/Github/invariMH/R/orthogonal_group.R")

```


```{r}

n <- 1
sig <- .1
t <- .3
s <- seq(0.01, .99, by = .001)
n_s <- length(s)

y <- rep(0, n_s)
z <- y

for (i in (1:n_s)) {
  y[i] <- g_bar(n, s[i], t, sig)
  z[i] <- sample_g_bar(t, sig)
}
plot(s, y)
hist(z, freq = FALSE, breaks = 15)
sum(z <= 0)
```
```{r}

sig <- .1
t1 <- 1
t2 <- 3
sig1 <- .5
sig2 <- .5
f_bar <- f_bar_conc_bimodal(t1, t2, sig1, sig2)

t <- seq(0.01, 4.99, length.out = 10000)
n_t <- length(t)

y <- rep(0, n_t)
for (i in (1:n_t)) {
  y[i] <- f_bar(t[i])
}
plot(t, y)




```





```{r}
n <- 2
r <- 1
n_samp <- 100
samples <- matrix(0, n, n_samp)
for (i in (1:n_samp)) {
  sample <- runif_sphere(n, r)
  samples[, i] <- sample
}

samples

plot(samples[1, ], samples[2, ])
```



```{r}
n <- 2
t1 <- 5 
t2 <- 10  
sig1 <- 1
sig2 <- 1

sig <- 1

f_bar <- f_bar_conc_bimodal(t1, t2, sig1, sig2)

t0 <- 2
n_samp <- 100000
samples_quotient <- qmh_orth_grp_quotient(n, f_bar, t0, n_samp, sig)

hist(samples_quotient[seq(1000, 100000, by = 200)], freq = FALSE, breaks = 15) 

samples <- qmh_orth_grp(n, f_bar, t0, n_samp, sig)
samples1 <- samples[seq(10000, 100000, by = 200), ]
plot(samples1[ , 1], samples1[ , 2], cex = .1)
```



