---
title: "Untitled"
output: pdf_document
date: "2024-11-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(MASS)
library(ggplot2)
```

```{r}
# functions: 

proj_u <- function(v, u, Sig) {
  vu <- as.numeric(crossprod(v, Sig %*% u))
  uu <- as.numeric(crossprod(u, Sig %*% u))
  p_v <- (vu / uu) * u
  return(p_v)
}

grahm_schimdt <- function(A, Sig) {
   # browser()
    n <- nrow(A)
    U <- matrix(0, n, n)
    E <- matrix(0, n, n)
    U[ , 1] <- A[ , 1]
    E[ , 1] <- U[ , 1] / as.numeric(crossprod(U[ , 1], Sig %*% U[ , 1]))^.5
    
    for (j in 2:n) {
      U[ , j] <- A[ , j]
        for (k in (1:(j-1))) {
          U[ , j] <- U[ , j] - proj_u(A[ , j], U[ , k], Sig)
        }
      
      E[ , j] <- U[, j, drop = FALSE] / as.numeric(crossprod(U[ , j], Sig %*% U[ , j]))^.5
    }
      
    return(E)
}

sample_haar_orthogonal_matrix <- function(Sig) {
  d <- nrow(Sig)
  X <- X <- matrix(rnorm(d^2), d, d)
  U <- grahm_schimdt(X, Sig)
  
  return(U)
}


sample_mixture <- function(n, d, k, mean_list, variance_list, component_probs) {
  
  samples <- matrix(0, n, d)
  components <- sample(x = (1:k), size = n, replace = TRUE, prob = component_probs)
  
  for (i in (1:n)) {
    component_i <- components[i]
    mean_i <- mean_list[[component_i]]
    variance_i <- variance_list[[component_i]]
    sample_i <- mvrnorm(n = 1, mu = mean_i, variance_i)
    
    samples[i, ] <- sample_i
  }
  
  samples_df <- data.frame(samples)
  samples_df$components <- components
  
  return(samples_df)
}
```

```{r}
# test grahm schmidt
z <- 3
A <- matrix(rnorm(z^2), z, z) 
Sig <- diag(z)

X <- grahm_schimdt(A, Sig)
crossprod(X)
```



```{r}
# sampling:

# number of samples
n <- 1000
# dimension of data
d <- 3
# number of components in mixture
k <- 3
# component probabilities
component_probs <- c(rep(1/3, k))
# component means
mean_list <- vector(mode = "list", length = k)
# component covariance matrices
variance_list <- vector(mode = "list", length = k)

# populate mean and variance lists
for (i in (1:k)) {
  mean_i <- runif(n = d, min = -20, max = 20)
  variance_i <- crossprod(matrix(runif(n = d^2, min = -3, max = 3), d, d))
  
  mean_list[[i]] <- mean_i
  variance_list[[i]] <- variance_i
}

samples <- sample_mixture(n, d, k, mean_list, variance_list, component_probs)
```

```{r}
# plotting:

samples_df <- data.frame(samples)
ggplot(samples_df) + geom_point(aes(x = X1, y = X2, color = as.factor(components)))
```

```{r}
# compress: 

samples_df_compressed <- samples_df[, c(d, d+1)]
samples_df_compressed$components <- samples_df$components

for (i in (1:n)) {
  sample_i <- t(samples_df[i, (1:d)])
  component_i <- samples_df$components[i]
  
  sig_i <- variance_list[[component_i]]
  eigen_sig_i <- eigen(sig_i)
  V <- eigen_sig_i$vectors
  Lam_sqrt <- diag(sqrt(eigen_sig_i$values))
  sig_i_sqrt <- V %*% Lam_sqrt %*% t(V)
  
  samples_df_compressed[i, 1] <- crossprod(sig_i_sqrt %*% sample_i)
}

head(samples_df_compressed)
```

```{r}
# Reconstruction
orthogonal_haar_samples <- vector(mode = "list", length = n)
for (i in (1:n)) {
  component_i <- samples_df_compressed$components[i]
  Sig_i <- variance_list[[component_i]]
  U_i <- sample_haar_orthogonal_matrix(Sig_i)
  orthogonal_haar_samples[[i]] <- U_i
}




```

